export const enum Paths {
  TimeKeeping = 'TimeSheet',
  Home = 'Home',
  Main = 'Main',
  Login = 'Login',
  Account = 'Account',
  Company = 'Company',
  Employeer = 'Employeer',
  LeaveList = 'LeaveList',
  EmployeerDetail = 'EmployeerDetail',
  Setting = 'Setting',
  MyLeaveList = 'MyLeaveList',
  CreateHoliday = 'CreateHoliday',
  PersonInfo = 'PersonInfo',
  ExpenseList = 'ExpenseList',
  MyExpenseList = 'MyExpenseList',
  CreateExpense = 'CreateExpense',
  Notification = 'Notification',
}
